
export const SET_SCORE_POSITIVE="SET_SCORE_POSITIVE";
export const SET_SCORE_NEGATIVE="SET_SCORE_NEGATIVE";
export const GET_RANDOM_WORD="GET_RANDOM_WORD";
export const GET_LETTER="GET_LETTER";
export const SUBMIT_COUNT="SUBMIT_COUNT";
export const SET_TIME="SET_TIME";
